language: go

go:
  - "1.10.x"
  - "1.11.x"
  - tip

cache: apt

addons:
  apt:
    update: true
    packages:
      - rpm

env:
  - GO111MODULE=on GOLANGCI_LINT_VERSION=1.13.2

script:
  - '[ "$(echo "$TRAVIS_GO_VERSION" | perl -pe "s/\\.[x\\d]+$//")" = "1.10" ] && go test -v ./... || go test -mod vendor -v ./...'
  - '[ "$(echo "$TRAVIS_GO_VERSION" | perl -pe "s/\\.[x\\d]+$//")" = "1.10" ] && go install || go build -mod=vendor'

jobs:
  include:
    - stage: golangci-lint
      go: "1.11.x"
      script:
        - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v${GOLANGCI_LINT_VERSION}
        - GO111MODULE=off golangci-lint run ./...
        - go test -v -mod=vendor ./...
        - go build -mod=vendor
    - stage: goreleaser
      go: "1.11.x"
      script:
        - curl -sL https://git.io/goreleaser | head -n -2 | bash
        - tar -xf /tmp/goreleaser.tar.gz -C $GOPATH/bin
        - goreleaser --snapshot --skip-sign
